name: Supabase Keepalive

on:
  workflow_dispatch:  # Allows manual triggering
  schedule:
    # Runs at every 5 minutes
    - cron: '*/5 * * * *'

jobs:
  keepalive:
    runs-on: ubuntu-latest
    steps:
      - name: Keep Supabase Active
        run: |
          echo "Keeping Supabase instance active..."
          
          # Simply make a request to the Supabase URL
          # The || true ensures the workflow always succeeds
          curl "${{ secrets.SUPABASE_URL }}" \
            --max-time 10 \
            --silent \
            --output /dev/null \
            --write-out "HTTP Status: %{http_code}\n" \
            || true
          
          echo "✅ Keepalive request sent - Supabase will stay active"
